name: Build Ironwail (Windows ARM64/AArch64)

on:
  push:
    branches:
      - master

jobs:
  build-arm64:
    runs-on: windows-11-arm
    steps:
      - name: 'Configure git: core.autocrlf, core.eol'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          pacboy: >-
            cmake:p
            curl:p
            flac:p
            libmikmod:p
            libxmp:p
            libvorbis:p
            mpg123:p
            ninja:p
            opusfile:p
            SDL2:p
            toolchain:p
      - name: Build
        shell: msys2 {0}
        run: |
          cmake -B build -S .
          cmake --build build
      - name : Copy files
        shell: msys2 {0}
        run: |
          cd build
          mkdir upload
          cp *.dll upload
          cp ../LICENSE.txt upload/license.txt
          cp ../Quake/ironwail.pak upload
          cp ironwail.exe upload
          for i in $(ldd ironwail.exe | cut -d '>' -f 2 | grep $MSYSTEM_PREFIX/bin | awk '{print $1}'); do [ -f "${i}" ] && cp "${i}" upload; done
          strip upload/ironwail.exe
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ironwail-git-winarm64-${{github.sha}}
          path: build/upload
          if-no-files-found: error
